### ISSUE TITLE
can't download SVG

### ISSUE THREAD

**Issue by nclemmons** [marvingreenberg/SOjoinery#13]
I can't seem to download an SVG from the screen. If I click on either the image or the .svg name I would expect it do download as an .svg

But it downloads as a .svg.txt and if I change to .svg it does not open properly.

On a Mac using latest OS with Graphic for an SVG editor.

**Comment by marvingreenberg** [comment]
Hmm.  It is working for me.  Can you post the url for the svg you geenrated, like
https://sojoinery.appspot.com/soboxjoint?boxjoint=True&bitdiam=0.25&thickness=0.75&width=7.0&units=in&ax=0.5

And then mouse over the image and right-click copy-link-address and post that URL?  For me it was,
https://sojoinery.appspot.com/svg/soboxjoint_pinface_7.000in_p_0.500.svg (for one of them)

Oh.  I think this is a Safari thing.  (I use Chrome everywhere).  If you right-click and choose **download-linked-file-as** (instead of just download-linked-file) I think it will work.  (It did for me).  There may be something I can do with mime-type or some other mysterious web thing to get it to work more naturally.

**Comment by nclemmons** [comment]
The URL:  https://sojoinery.appspot.com/sodovetail?gutter=0.2&pinangle=7.0&bitdiam=0.125&thickness=0.75&width=10.0&units=in&ax=3.0&bx=0.5

The SVG copy:  
https://sojoinery.appspot.com/svg/sodovetail_pinface_10.000in_a_4.286_b_0.714.svg

The file that's downloaded:
sodovetail_pinface_10.000in_a_4.286_b_0.714.svg.txt

Not sure why it's downloading an a .txt file on my MacBook Pro in Safari.
If I go to the Noun Project or other SVG's I find online and click on them, they download as .svg

**Comment by nclemmons** [comment]
Clicking on 'download as' in safari still saves it as .txt file even when it is set as .svg

**Comment by nclemmons** [comment]
I mentioned on shaper community the idea of adding blue text to show where cuts are.  Something like this...

<img width="760" alt="cut here" src="https://user-images.githubusercontent.com/47183619/52062172-9da76b00-2535-11e9-8c7c-36a67f906987.png">

**Comment by nclemmons** [comment]
If I remove the .txt in the file that is downloaded it does open as .svg so something seems to be happening with your code...

**Comment by marvingreenberg** [comment]
I'll talk about your comment about the text over on Community tonight sometime.  Meanwhile #13 is fixed - unfortunately I can't figure something out about google's cloud and can't really work on it during the day.  The fix is deployed, I just am too new to google's platform to tell it to use it for some reason.

Try https://0b3-dot-bulbous.appspot.com

**Comment by nclemmons** [comment]
That worked.  It now downloads as a .svg file and opens fine.

For some reason, Graphic makes stroke widths really wide but those are easy to change in tool.  Do you set a stroke width in your file/

ALSO, Looks like you have the click zone as a larger rectangle over the text link and the image.  Might make sense to make them two different click to download zones.

**Comment by marvingreenberg** [comment]
OK, I figured out why it wasn't deploying.  Should be good now.
